// U.S. House by County: https://www2.census.gov/geo/relfiles/cdsld13/12/co_cd_12.txt
// Upper by County: http://www2.census.gov/geo/relfiles/cdsld16/12/co_lu_12.txt
// Lower by County: https://www2.census.gov/geo/relfiles/cdsld16/12/co_ll_12.txt

export interface CountyInfo {
  county: string;
  unitedStateHouseDistricts: number[];
  stateSenateDistricts: number[];
  stateHouseDistricts: number[];
}

export const CountyInformation: CountyInfo[] = [
  {county: 'Alachua', unitedStateHouseDistricts: [3, 5], stateSenateDistricts: [8], stateHouseDistricts: [10, 20, 21]},
  {county: 'Baker', unitedStateHouseDistricts: [4], stateSenateDistricts: [5], stateHouseDistricts: [10]},
  {county: 'Bay', unitedStateHouseDistricts: [2], stateSenateDistricts: [2], stateHouseDistricts: [5, 6]},
  {county: 'Bradford', unitedStateHouseDistricts: [3], stateSenateDistricts: [5], stateHouseDistricts: [19]},
  {county: 'Brevard', unitedStateHouseDistricts: [8], stateSenateDistricts: [14, 17], stateHouseDistricts: [50, 51, 52, 53]},
  {county: 'Broward', unitedStateHouseDistricts: [20, 21, 22, 23, 24, 25], stateSenateDistricts: [29, 32, 33, 34, 35], stateHouseDistricts: [92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105]},
  {county: 'Calhoun', unitedStateHouseDistricts: [2], stateSenateDistricts: [3], stateHouseDistricts: [7]},
  {county: 'Charlotte', unitedStateHouseDistricts: [17], stateSenateDistricts: [23, 26], stateHouseDistricts: [75]},
  {county: 'Citrus', unitedStateHouseDistricts: [11], stateSenateDistricts: [10], stateHouseDistricts: [34]},
  {county: 'Clay', unitedStateHouseDistricts: [3, 5], stateSenateDistricts: [5], stateHouseDistricts: [18, 19]},
  {county: 'Collier', unitedStateHouseDistricts: [19, 25], stateSenateDistricts: [28], stateHouseDistricts: [80, 105, 106]},
  {county: 'Columbia', unitedStateHouseDistricts: [3], stateSenateDistricts: [5], stateHouseDistricts: [10]},
  {county: 'DeSoto', unitedStateHouseDistricts: [17], stateSenateDistricts: [26], stateHouseDistricts: [56]},
  {county: 'Dixie', unitedStateHouseDistricts: [3], stateSenateDistricts: [5], stateHouseDistricts: [21]},
  {county: 'Duval', unitedStateHouseDistricts: [4, 5], stateSenateDistricts: [4, 6], stateHouseDistricts: [11, 12, 13, 14, 15, 16]},
  {county: 'Escambia', unitedStateHouseDistricts: [1], stateSenateDistricts: [1], stateHouseDistricts: [1, 2]},
  {county: 'Flagler', unitedStateHouseDistricts: [6], stateSenateDistricts: [7], stateHouseDistricts: [24]},
  {county: 'Franklin', unitedStateHouseDistricts: [2], stateSenateDistricts: [3], stateHouseDistricts: [7]},
  {county: 'Gadsden', unitedStateHouseDistricts: [2], stateSenateDistricts: [3], stateHouseDistricts: [8]},
  {county: 'Gilchrist', unitedStateHouseDistricts: [3], stateSenateDistricts: [5], stateHouseDistricts: [21]},
  {county: 'Glades', unitedStateHouseDistricts: [17], stateSenateDistricts: [26], stateHouseDistricts: [55]},
  {county: 'Gulf', unitedStateHouseDistricts: [2], stateSenateDistricts: [3], stateHouseDistricts: [7]},
  {county: 'Hamilton', unitedStateHouseDistricts: [3], stateSenateDistricts: [3], stateHouseDistricts: [10]},
  {county: 'Hardee', unitedStateHouseDistricts: [17], stateSenateDistricts: [26], stateHouseDistricts: [56]},
  {county: 'Hendry', unitedStateHouseDistricts: [20, 25], stateSenateDistricts: [28], stateHouseDistricts: [80]},
  {county: 'Hernando', unitedStateHouseDistricts: [11], stateSenateDistricts: [10], stateHouseDistricts: [34, 35]},
  {county: 'Highlands', unitedStateHouseDistricts: [17], stateSenateDistricts: [26], stateHouseDistricts: [55]},
  {county: 'Hillsborough', unitedStateHouseDistricts: [12, 14, 15, 17], stateSenateDistricts: [18, 19, 20, 21], stateHouseDistricts: [57, 58, 59, 60, 61, 62, 63, 64, 70]},
  {county: 'Holmes', unitedStateHouseDistricts: [1, 2], stateSenateDistricts: [2], stateHouseDistricts: [5]},
  {county: 'Indian', unitedStateHouseDistricts: [8], stateSenateDistricts: [17], stateHouseDistricts: [54]},
  {county: 'Jackson', unitedStateHouseDistricts: [2], stateSenateDistricts: [2], stateHouseDistricts: [5]},
  {county: 'Jefferson', unitedStateHouseDistricts: [2], stateSenateDistricts: [3], stateHouseDistricts: [7]},
  {county: 'Lafayette', unitedStateHouseDistricts: [3], stateSenateDistricts: [5], stateHouseDistricts: [7]},
  {county: 'Lake', unitedStateHouseDistricts: [5, 10, 11], stateSenateDistricts: [12, 22], stateHouseDistricts: [31, 32, 33]},
  {county: 'Lee', unitedStateHouseDistricts: [17, 19], stateSenateDistricts: [26, 27, 28], stateHouseDistricts: [76, 77, 78, 79]},
  {county: 'Leon', unitedStateHouseDistricts: [2], stateSenateDistricts: [3], stateHouseDistricts: [7, 8, 9]},
  {county: 'Levy', unitedStateHouseDistricts: [3], stateSenateDistricts: [5], stateHouseDistricts: [22]},
  {county: 'Liberty', unitedStateHouseDistricts: [2], stateSenateDistricts: [3], stateHouseDistricts: [7]},
  {county: 'Madison', unitedStateHouseDistricts: [2, 3], stateSenateDistricts: [3], stateHouseDistricts: [7]},
  {county: 'Manatee', unitedStateHouseDistricts: [16, 17], stateSenateDistricts: [21], stateHouseDistricts: [70, 71, 73]},
  {county: 'Marion', unitedStateHouseDistricts: [3, 5, 11], stateSenateDistricts: [5, 8, 12], stateHouseDistricts: [20, 22, 23, 33]},
  {county: 'Martin', unitedStateHouseDistricts: [18], stateSenateDistricts: [25], stateHouseDistricts: [82, 83]},
  {county: 'Miami', unitedStateHouseDistricts: [23, 24, 25, 26, 27], stateSenateDistricts: [35, 36, 37, 38, 39, 40], stateHouseDistricts: [100, 102, 103, 105, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]},
  {county: 'Monroe', unitedStateHouseDistricts: [26], stateSenateDistricts: [39], stateHouseDistricts: [120]},
  {county: 'Nassau', unitedStateHouseDistricts: [4], stateSenateDistricts: [4], stateHouseDistricts: [11]},
  {county: 'Okaloosa', unitedStateHouseDistricts: [1], stateSenateDistricts: [1, 2], stateHouseDistricts: [3, 4]},
  {county: 'Okeechobee', unitedStateHouseDistricts: [17], stateSenateDistricts: [26], stateHouseDistricts: [55]},
  {county: 'Orange', unitedStateHouseDistricts: [5, 7, 8, 9, 10], stateSenateDistricts: [11, 13, 15], stateHouseDistricts: [30, 31, 44, 45, 46, 47, 48, 49, 50]},
  {county: 'Osceola', unitedStateHouseDistricts: [9], stateSenateDistricts: [15], stateHouseDistricts: [39, 42, 43]},
  {county: 'Palm', unitedStateHouseDistricts: [18, 20, 21, 22], stateSenateDistricts: [25, 29, 30, 31], stateHouseDistricts: [81, 82, 85, 86, 87, 88, 89, 90, 91]},
  {county: 'Pasco', unitedStateHouseDistricts: [12], stateSenateDistricts: [10, 16, 20], stateHouseDistricts: [36, 37, 38]},
  {county: 'Pinellas', unitedStateHouseDistricts: [12, 13, 14], stateSenateDistricts: [16, 19, 24], stateHouseDistricts: [64, 65, 66, 67, 68, 69, 70]},
  {county: 'Polk', unitedStateHouseDistricts: [9, 10, 15, 17], stateSenateDistricts: [20, 22, 26], stateHouseDistricts: [39, 40, 41, 42, 56]},
  {county: 'Putnam', unitedStateHouseDistricts: [5, 6], stateSenateDistricts: [8], stateHouseDistricts: [19]},
  {county: 'Santa', unitedStateHouseDistricts: [1], stateSenateDistricts: [1], stateHouseDistricts: [2, 3]},
  {county: 'Sarasota', unitedStateHouseDistricts: [16], stateSenateDistricts: [23], stateHouseDistricts: [70, 71, 72, 73, 74]},
  {county: 'Seminole', unitedStateHouseDistricts: [5, 7], stateSenateDistricts: [9], stateHouseDistricts: [28, 29, 30]},
  {county: 'St. Johns', unitedStateHouseDistricts: [6], stateSenateDistricts: [7], stateHouseDistricts: [17, 24]},
  {county: 'St. Lucie', unitedStateHouseDistricts: [18], stateSenateDistricts: [25], stateHouseDistricts: [54, 55, 83, 84]},
  {county: 'Sumter', unitedStateHouseDistricts: [11], stateSenateDistricts: [12], stateHouseDistricts: [33]},
  {county: 'Suwannee', unitedStateHouseDistricts: [3], stateSenateDistricts: [5], stateHouseDistricts: [10]},
  {county: 'Taylor', unitedStateHouseDistricts: [2], stateSenateDistricts: [3], stateHouseDistricts: [7]},
  {county: 'Union', unitedStateHouseDistricts: [3], stateSenateDistricts: [5], stateHouseDistricts: [19]},
  {county: 'Volusia', unitedStateHouseDistricts: [6, 7], stateSenateDistricts: [7, 9, 14], stateHouseDistricts: [24, 25, 26, 27]},
  {county: 'Wakulla', unitedStateHouseDistricts: [2], stateSenateDistricts: [3], stateHouseDistricts: [7]},
  {county: 'Walton', unitedStateHouseDistricts: [1], stateSenateDistricts: [2], stateHouseDistricts: [5]},
  {county: 'Washington', unitedStateHouseDistricts: [2], stateSenateDistricts: [2], stateHouseDistricts: [5]}
];
